const Images = [
  {image: require('../assets/banners/food-banner1.jpg')},
  {image: require('../assets/banners/food-banner2.jpg')},
  {image: require('../assets/banners/food-banner3.jpg')},
  {image: require('../assets/banners/food-banner4.jpg')},
  {image: require('../assets/banners/food-banner5.jpg')},
  {image: require('../assets/banners/food-banner6.jpg')},
  {image: require('../assets/banners/food-banner7.jpg')},
];

export const data = [
  {
    id: '1',
    coordinate: {
      latitude: 22.6293867,
      longitude: 88.4354486,
    },
    title: 'Bunny - Food & Drink - Thi Sách',
    description:"Thức ăn ngon",
    address: `34/H07/17 Thi Sách, P. Hòa Thuận Tây, Quận Hải Châu, Đà Nẵng.`,
    image: Images[0].image,
    rating: 4,
    reviews: 99,
    categories: ['Nhà hàng', 'Cửa hàng', 'Bữa tối'],
  },
  {
    id: '2',
    coordinate: {
      latitude: 22.6345648,
      longitude: 88.4377279,
    },
    description:"Thức ăn ngon",
    title: 'Chiang Coffee',
    address: `Lô 14 - B2.1 Trường Thi 6, P. Hòa Thuận Tây, Quận Hải Châu, Đà Nẵng.`,
    image: Images[1].image,
    rating: 5,
    reviews: 102,
    categories: ['Nhà hàng', 'Thức ăn nhanh', 'Góc ăn vặt'],
  },
  {
    id: '3',
    coordinate: {
      latitude: 22.6281662,
      longitude: 88.4410113,
    },
    description:"Thức ăn ngon",
    title: 'Cơm Chiên Giòn - Nguyễn Tri Phương',
    address: `95 Nguyễn Tri Phương, P. Thạc Gián, Quận Thanh Khê, Đà Nẵng.`,
    image: Images[2].image,
    rating: 3,
    reviews: 220,
    categories: ['Nhà hàng', 'Cửa hàng', 'Bữa tối'],
  },
  {
    id: '4',
    coordinate: {
      latitude: 22.6341137,
      longitude: 88.4497463,
    },
    description:"Thức ăn ngon",
    title: 'Bần Mà Sang - Tiệm Ăn Vặt',
    address: `203/12A Nguyễn Tri Phương, P. Hòa Thuận Nam, Quận Hải Châu, Đà Nẵng.`,
    image: Images[3].image,
    rating: 4,
    reviews: 48,
    categories: ['Nhà hàng', 'Thức ăn nhanh', 'Góc ăn vặt'],
  },
  {
    id: '5',
    coordinate: {
      latitude: 22.6292757,
      longitude: 88.444781,
    },
    title: 'TeamUp Coffee - Lê Đình Lý',
    description:"Thức ăn ngon",
    address: `189 Lê Đình Lý, P. Hòa Thuận Tây, Quận Hải Châu, Đà Nẵng.`,
    image: Images[4].image,
    rating: 4,
    reviews: 178,
    categories: ['Nhà hàng', 'Cửa hàng', 'Bữa tối'],
  },
  {
    id: '6',
    coordinate: {
      latitude: 22.6293867,
      longitude: 88.4354486,
    },
    title: 'Mr Bob - Xôi & Bánh Mỳ',
    description:"Thức ăn ngon",
    address: `166 Lê Đình Lý, P. Vĩnh Trung, Quận Thanh Khê, Đà Nẵng.`,
    image: Images[5].image,
    rating: 4,
    reviews: 99,
    categories: ['Nhà hàng', 'Cửa hàng', 'Bữa tối'],
  },
  {
    id: '7',
    coordinate: {
      latitude: 22.6345648,
      longitude: 88.4377279,
    },
    title: 'Cơm Bếp Việt',
    description:"Thức ăn ngon",
    address: `166 Lê Đình Lý, P. Hòa Thuận Đông, Quận Hải Châu, Đà Nẵng.`,
    image: Images[6].image,
    rating: 5,
    reviews: 102,
    categories: ['Nhà hàng', 'Thức ăn nhanh', 'Góc ăn vặt'],
  },
];
